language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_install:
- git config --global user.name 'yunweichen'
- git config --global user.email 352298694@qq.com
install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install
script:
- hexo clean
- hexo g
- hexo d
