language: node_js
node_js:
- stable
branches:
  only:
  - master
before_install:
- git config --global user.name 'yunweichen'
- git config --global user.email 352298694@qq.com
install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install --save hexo-filter-flowchart
- npm install --save hexo-filter-sequence
- npm install
script:
- hexo clean
- hexo g
#- hexo d
after_script:
- cd ./public
- git init
- git add .
- git commit -m "TravisCI 自动部署"
# Github Pages
- git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master 
# Coding Pages
#- git push --force --quiet "https://coding用户名:${CO_TOKEN}@${CO_REF}" master:master

env:
 global:
   # Github Pages
   - GH_REF: git@github.com:yunweichen/yunweichen.github.io  #这里替换你的github仓库地址
   # Coding Pages
   # - CO_REF: git.coding.net/bule/bule.coding.me.git  这里替换你的coding仓库地址
